import initInboundDataSyncEventListener from './inboundDataSyncEventListener';
import { initSaveEventListener } from './saveEventListener';
import { initRemoveAndHideEventListeners } from './removeAndHideEventListeners';
import initChoiceAndToggleEventListeners from './choiceAndToggleEventListeners';
import initInputElementEventListener from './inputElementEventListener';
import initFileUploadEventListeners from './fileUpload';
import initClickToSaveEventListener from './clickToSaveEventListener';
import { callWatchFunctions, callMultipleWatchFunctions, getValueAndDataSourceElemFromKeyName } from './watchHelpers';
import { afterSync } from "./syncData";
import optionsData from './optionsData';
import { enableSaveAttribute, initSaveFunctions, callSaveFunction } from './onSave';
import initEditableAttribute from './editableAttribute';
import initAddingItemEventListener from './addingItemEventListener';
import initSortableElements from './sortableElements';
import initAutoGeneratedComponents from './autoGeneratedComponents';

const merge = require('lodash/merge');

function initInputEventListeners (options) {
  merge(optionsData, options);
  
  initAutoGeneratedComponents(); // this creates element, so it should come first
  
  enableSaveAttribute(afterSync);
  initInboundDataSyncEventListener();
  initSaveEventListener();
  initRemoveAndHideEventListeners();
  initChoiceAndToggleEventListeners();
  initInputElementEventListener();
  initFileUploadEventListeners();
  initClickToSaveEventListener();
  initEditableAttribute();
  initAddingItemEventListener();

  if (optionsData.sortable) {
    initSortableElements();
  }
}

export {
  initInputEventListeners,
  initSaveFunctions,
  callSaveFunction,
  callWatchFunctions,
  callMultipleWatchFunctions,
  getValueAndDataSourceElemFromKeyName
}





