import { initRemoveAndHideEventListeners } from './removeAndHideEventListeners';
import initEventsForUpdatingData from './eventsForUpdatingData';
import initClickToSaveEventListener from './clickToSaveEventListener';
import optionsData from './optionsData';
import { onSave, onFileUpload, onFileUploadProgress, onAddItem, onSync } from './callbacks';
import { 
  initSaveFunctions, 
  callSaveFunction
} from './onSave';
import initEditableAttribute from './editableAttribute';
import initAddingItemEventListener from './addingItemEventListener';
import initSortableElements from './sortableElements';
import initAutoGeneratedComponents from './autoGeneratedComponents';

const merge = require('lodash/merge');

function init (options) {
  merge(optionsData, options);
  
  initAutoGeneratedComponents(); // this creates element, so it should come first
  
  initSaveFunctions();
  initRemoveAndHideEventListeners();
  initEventsForUpdatingData();
  initClickToSaveEventListener();
  initEditableAttribute();
  initAddingItemEventListener();

  if (optionsData.sortable) {
    initSortableElements();
  }
}

export {
  init,
  callSaveFunction,
  onSave,
  onFileUpload,
  onFileUploadProgress,
  onAddItem,
  onSync
}





